# Generated by Django 2.2.6 on 2020-01-05 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0009_auto_20200103_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100, verbose_name='Nome do Projeto')),
                ('description', models.TextField(blank=True, verbose_name='Descrição do Projeto')),
                ('create_project', models.DateTimeField(auto_now_add=True)),
                ('update_project', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='residencdimens',
            name='update_resid',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='residencdimens',
            name='projeto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cable.Project', verbose_name='Nome do Projeto'),
            preserve_default=False,
        ),
    ]
